### ISSUE TITLE
Mobile App - Customer Login

### ISSUE THREAD

**Issue by lucreck** [Haravan/docs#1]
Hiện tại mình có thấy trên mobile app vinamilk khách hàng có thể đăng ký và đăng nhập được, có ai biết là họ làm thế nào không?

**Comment by lmcuong25** [comment]
hi lucreck,

có 2 cách để làm:

cách 1: nhúng webview

cách 2: thu thập data và  post vào form login giống trên web ( debug network xem web post vào link nào, data gì thì mình làm giống như vậy )

để check user đã login hay chưa, thì có thể get cookie của webview để check, hoặc tạo trong theme một view trả về customer_id của khách đã login.

**Comment by lucreck** [comment]
Dạ, Thank a.
